defaults:
  - _self_
  - task: real_drawer

name: train_edm_real_drawer
_target_: consistency_policy.student.ctm_workspace.CTMWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: ${task.name}


checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-val_mse_error={val_mse_error:.3f}.ckpt
    k: 10
    mode: min
    monitor_key: val_mse_error
dataloader:
  batch_size: 64 #64
  num_workers: 8 #16
  persistent_workers: true
  pin_memory: true
  shuffle: true

val_dataloader:
  batch_size: 64 #64
  num_workers: 8 #16
  persistent_workers: true
  pin_memory: true
  shuffle: false

dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
# exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: ctm-student-bz64
  project: consistency-policy-student
  resume: false
multi_run:
  run_dir: data/outputs/cd/square/ctmpp
  wandb_name_base: dsm_test
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
# name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: consistency_policy.student.ctm_policy.CTMPPUnetHybridImagePolicy
  inference_mode: none # this will be populated automatically from training.inference_mode, do not set it here
  cond_predict_scale: true
  crop_shape:
  - 108
  - 144
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  dropout_rate: 0.2
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  #extra args
  initial_ema_decay: 0.0
  delta: -1 #0.0068305197 # sqrt(160) * .00054
  special_skip: true
  chaining_times: ['D', 27, 54]
  #teacher
  teacher_path: /home/clear/consistency-policy/outputs/edm/real_drawer/checkpoints/latest.ckpt 
  #KDE
  use_kde: False
  kde_samples: 0
  #warm start
  edm: /home/clear/consistency-policy/outputs/edm/real_drawer/checkpoints/latest.ckpt  #mse 0.033#???   # teacher 模型 checkpoint文件路径
  losses: [["ctm", "dsm"], [1, 1]]
  ctm_sampler: ctm
  dsm_weights: "karras"
  noise_scheduler:
    _target_: consistency_policy.diffusion.CTM_Scheduler
    time_min: 0.02
    time_max: 80.0
    rho: 7.0
    bins: 80
    solver: heun
    scaling: boundary
    use_c_in: true
    data_std: .5
    time_sampler: ctm
    clamp: true
    ode_steps_max: 1
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  shape_meta: ${task.shape_meta}

training:
  inference_mode: false # Setting this to true disables the teacher, warm start, and training loop
  online_rollouts: false # Setting this to false disables the env_runner
  debug: false
  checkpoint_every: 50
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 500
  resume: false
  resume_path: ???
  rollout_every: 50
  sample_every: 50
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 50
  val_sample_every: 50
  output_dir: outputs/cd/real_drawer/
  val_chaining_steps: 1
  p_epochs: 400
